language: cpp
compiler: gcc
dist: bionic

install: 
  - sudo apt update -qq
  # Boost
  - sudo apt install -qq libboost-all-dev
  # Qt5
  - sudo apt-get install -qq libqt5webkit5-dev qtdeclarative5-dev
  - export QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake
  # GraphViz
  - sudo apt-get install -qq graphviz
  # dot2tex
  - sudo apt-get install -qq dot2tex
  # Poppler
  - sudo apt-get install libpoppler-qt5-dev

services:
 - xvfb

script: 
  - qmake
  - make debug --silent
  # Do not run on Travis
  # - ./boost_graph_example_4
